--
-- Initial DB preferences
--

-- author: Dmitry Ovchinnikov

SET DATABASE DEFAULT TABLE TYPE CACHED;
SET DATABASE EVENT LOG LEVEL 2;
SET DATABASE GC 10000;
SET DATABASE TRANSACTION CONTROL LOCKS;
SET DATABASE DEFAULT ISOLATION LEVEL SERIALIZABLE;
SET FILES CACHE ROWS 10000;
SET FILES CACHE SIZE 10000;
SET FILES DEFRAG 30;
SET FILES LOG TRUE;
SET FILES NIO FALSE;
SET FILES WRITE DELAY 1;
SET FILES SCALE 8;
SET FILES LOB SCALE 1;
SET FILES LOB COMPRESSED FALSE;
SET FILES SCRIPT FORMAT COMPRESSED;

